apiVersion: v1
kind: LimitRange
metadata:
  name: limit-container
spec:
  limits:
    - type: Container
      default:
        cpu: 150m
        memory: 128Mi
      max:
        cpu: 5000m
        memory: 512Mi
      min:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 150m
        memory: 128Mi
