apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
        - name: httpd-app
          image: httpd
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: priority
      #               operator: Exists
      #               # values:
      #               #   - "1"
      #               #   - "2"
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - preference:
      #           matchExpressions:
      #             - key: priority
      #               operator: In
      #               values:
      #                 - "1"
      #         weight: 1
