apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid # Forbid: Dont start other jobs, Replace: Replace existing jobs, Accept: Accept new jobs
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      parallelism: 4
      backoffLimit: 20
      completions: 3
      template:
        spec:
          containers:
            - name: hello
              image: busybox:1.28
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
