apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOne # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: "/volumes/mongodb"
