apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-volume-claim-digital-ocean
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: do-block-storage-retain
  resources:
    requests:
      storage: 5Gi
  # volumeMode: Filesystem
