apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-deployment
          image: nginx
          lifecycle:
            postStart:
              exec:
                command:
                  - "curl"
                  - "<some url>"
            preStop:
              exec:
                command:
                  - "curl"
                  - "<some url>"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
