apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-jsdtech-app-cert
spec:
  secretName: jsdtech-app-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - jsdtech.app
