apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  selector:
    matchLabels:
      app: dashboard-app
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      serviceAccount: user-claim
      containers:
      - name: dashboard-app
        image: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

