apiVersion: rbac.authorization.k8s.io/v1
kind: Role # ClusterRole
metadata:
  name: app-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # ClusterRoleBinding
metadata:
  name: app-reader-binding
subjects:
  - kind: ServiceAccount
    name: user-claim
    namespace: default
roleRef:
  kind: Role # ClusterRole
  name: app-reader
  apiGroup: rbac.authorization.k8s.io