apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: nginx-svc
  replicas: 7
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      initContainers:
        - name: volume-page
          image: busybox
          command:
            ["sh", "-c", "echo $(hostname) > /usr/share/nginx/html/index.html"]
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      containers:
        - name: nginx-app
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage-retain
        resources:
          requests:
            storage: 1Gi
