apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo-db
    spec:
      containers:
        - name: mongo-container
          image: mongo:{{ .Values.mongodb.tag }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongodb-pvc

