apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
spec:
  selector:
    app: {{ .Release.Name }}-mongo-db
  ports:
    - port: 27017
      targetPort: 27017
      name: http
  type: ClusterIP
